# Services

services:
  # ChirpStack
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - "8080:8080"
    networks:
      - chirpstack-network

  # ChirpStack Gateway Bridge
  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-eu868.toml
    ports:
      - "1700:1700/udp"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
    networks:
      - chirpstack-network

  # PostgreSQL
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chirpstack"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - chirpstack-network

  # Redis
  redis:
    image: redis:8.0
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data
    networks:
      - chirpstack-network

  # Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    restart: unless-stopped
    volumes:
      - ./configuration/mosquitto/config/:/mosquitto/config/
    networks:
      - chirpstack-network

# Volumes
volumes:
  postgresqldata:
  redisdata:

# Networks
networks:
  chirpstack-network:
    driver: bridge
